module.exports.products=[
    {
        name:"Banana",
        category:"Fruit",
        stock:120,
        userId:"eNfHAIAhXHTiMDseozHZ5Ak8nMI2",
        price:25
    },{
        name:"Harbara",
        category:"Pulses",
        stock:230,
        userId:"eNfHAIAhXHTiMDseozHZ5Ak8nMI2",
        price:70
    },
    {
        name:"Brinjal",
        category:"Vegetable",
        stock:320,
        userId:"eNfHAIAhXHTiMDseozHZ5Ak8nMI2",
        price:46
    },
    {
        name:"Onion",
        category:"Vegetable",
        stock:50,
        userId:"xY8fPvkCnSdYpzpMyT9lyQsI99M2",
        price:43
    },
    
    {
        name:"Cabbage",
        category:"Vegetable",
        stock:310,
        userId: "RQt0WNBiQhNE8XxUMdf6psI7J8E2",
        price: 40
    },{
        name:"Cauliflower",
        category:"Vegetable",
        stock:270,
        userId:"RQt0WNBiQhNE8XxUMdf6psI7J8E2",
        price:35
    },
    {
        name:"Bottle Gourd",
        category:"Vegetable",
        stock:170,
        userId:"RQt0WNBiQhNE8XxUMdf6psI7J8E2",
        price:41
    },
    {
        name:"Brinjal",
        category:"Vegetable",
        stock:150,
        userId:"Badlapur",
        price:30
    },{
        name:"Tomato",
        category:"Vegetable",
        stock:120,
        userId:"Badlapur",
        price:30
    },
    {
        name:"Pumpkin",
        category:"Vegetable",
        stock:190,
        userId:"Badlapur",
        price:30
    },
    {
        name:"Onion",
        category:"Vegetable",
        stock:250,
        userId:"gD0qUXEUWeMsXJa8F77NhdwDWqI2",
        price:43
    },
    
    {
        name:"Potato",
        category:"Vegetable",
        stock:220,
        userId:"Solapur",
        price:45
    },{
        name:"Lady's Finger",
        category:"Vegetable",
        stock:190,
        userId:"Solapur",
        price:57
    },
    {
        name:"Bottle Gourd",
        category:"Vegetable",
        stock:700,
        userId:"Solapur",
        price:41
    },
    {
        name:"Harbara",
        category:"Pulses",
        stock:440,
        userId:"LWzbgWnqEFMJkzKH03SN78lZvzo1",
        price:70
    },
    {
        name:"Orange",
        category:"Fruit",
        stock:420,
        userId:"HfZ1BJYCD6OjeMhGkQHusrSF6Nm2",
        price:70
    },
]