module.exports.products=[
    {
        name:"Potato",
        category:"Vegetable",
        stock:12,
        userId:"abc",
        price:30
    },{
        name:"Tomato",
        category:"Vegetable",
        stock:43,
        userId:"abc",
        price:30
    },
    {
        name:"Onion",
        category:"Vegetable",
        stock:32,
        userId:"abc",
        price:30
    },
    {
        name:"Onion",
        category:"Vegetable",
        stock:19,
        userId:"def",
        price:30
    },{
        name:"Brinjal",
        category:"Vegetable",
        stock:54,
        userId:"def",
        price:30
    },
    {
        name:"Cabbage",
        category:"Vegetable",
        stock:29,
        userId:"def",
        price:30
    },
    {
        name:"Cabbage",
        category:"Vegetable",
        stock:31,
        userId:"geh"
    },{
        name:"Cauliflower",
        category:"Vegetable",
        stock:27,
        userId:"geh",
        price:30
    },
    {
        name:"Bottle Gourd",
        category:"Vegetable",
        stock:17,
        userId:"geh",
        price:30
    },
    {
        name:"Brinjal",
        category:"Vegetable",
        stock:15,
        userId:"hij",
        price:30
    },{
        name:"Tomato",
        category:"Vegetable",
        stock:12,
        userId:"hij",
        price:30
    },
    {
        name:"Pumpkin",
        category:"Vegetable",
        stock:19,
        userId:"hij",
        price:30
    },
    {
        name:"Bottle Gourd",
        category:"Vegetable",
        stock:25,
        userId:"ijk",
        price:30
    },{
        name:"Carrot",
        category:"Vegetable",
        stock:33,
        userId:"ijk",
        price:30
    },
    {
        name:"Okra",
        category:"Vegetable",
        stock:26,
        userId:"ijk",
        price:30
    },
    {
        name:"Potato",
        category:"Vegetable",
        stock:22,
        userId:"nmp",
        price:30
    },{
        name:"Okra",
        category:"Vegetable",
        stock:19,
        userId:"nmp",
        price:30
    },
    {
        name:"Bottle Gourd",
        category:"Vegetable",
        stock:7,
        userId:"nmp",
        price:30
    },
    {
        name:"Cabbage",
        category:"Vegetable",
        stock:44,
        userId:"lmn",
        price:30
    },{
        name:"Okra",
        category:"Vegetable",
        stock:11,
        userId:"lmn",
        price:30
    },
    {
        name:"Onion",
        category:"Vegetable",
        stock:32,
        userId:"lmn",
        price:30
    }
]