module.exports.products=[
    {
        name:"Potato",
        category:"Vegetable",
        stock:120,
        userId:"abc",
        price:30
    },{
        name:"Tomato",
        category:"Vegetable",
        stock:430,
        userId:"abc",
        price:30
    },
    {
        name:"Onion",
        category:"Vegetable",
        stock:320,
        userId:"abc",
        price:30
    },
    {
        name:"Onion",
        category:"Vegetable",
        stock:190,
        userId:"def",
        price:30
    },{
        name:"Brinjal",
        category:"Vegetable",
        stock:540,
        userId:"def",
        price:30
    },
    {
        name:"Cabbage",
        category:"Vegetable",
        stock:290,
        userId:"def",
        price:30
    },
    {
        name:"Cabbage",
        category:"Vegetable",
        stock:310,
        userId:"geh"
    },{
        name:"Cauliflower",
        category:"Vegetable",
        stock:270,
        userId:"geh",
        price:30
    },
    {
        name:"Bottle Gourd",
        category:"Vegetable",
        stock:170,
        userId:"geh",
        price:30
    },
    {
        name:"Brinjal",
        category:"Vegetable",
        stock:150,
        userId:"hij",
        price:30
    },{
        name:"Tomato",
        category:"Vegetable",
        stock:120,
        userId:"hij",
        price:30
    },
    {
        name:"Pumpkin",
        category:"Vegetable",
        stock:190,
        userId:"hij",
        price:30
    },
    {
        name:"Bottle Gourd",
        category:"Vegetable",
        stock:250,
        userId:"ijk",
        price:30
    },{
        name:"Carrot",
        category:"Vegetable",
        stock:330,
        userId:"ijk",
        price:30
    },
    {
        name:"Okra",
        category:"Vegetable",
        stock:260,
        userId:"ijk",
        price:30
    },
    {
        name:"Potato",
        category:"Vegetable",
        stock:220,
        userId:"nmp",
        price:30
    },{
        name:"Okra",
        category:"Vegetable",
        stock:190,
        userId:"nmp",
        price:30
    },
    {
        name:"Bottle Gourd",
        category:"Vegetable",
        stock:700,
        userId:"nmp",
        price:30
    },
    {
        name:"Cabbage",
        category:"Vegetable",
        stock:440,
        userId:"lmn",
        price:30
    },{
        name:"Okra",
        category:"Vegetable",
        stock:110,
        userId:"lmn",
        price:30
    },
    {
        name:"Onion",
        category:"Vegetable",
        stock:320,
        userId:"lmn",
        price:30
    }
]