module.exports.users=[
    {
        _id:"Jalgaon",
        name:"Nishant",
        email:"ni@g.com",
        address:"Jalgaon",
        pincode:"412005",
        role:"farmer"
    },
    {
        _id:"Nashik",
        name:"Naman",
        email:"na@g.com",
        address:"Nashik",
        pincode:"420003",
        role:"farmer"
    },
    {
        _id:"Virar",
        name:"Sachit",
        email:"sa@g.com",
        address:"Virar",
        pincode:"401203",
        role:"farmer"
    },{
        _id:"Badlapur",
        name:"Abhishek",
        email:"ab@g.com",
        address:"Badlapur",
        pincode:"421503",
        role:"farmer"
    },
    {
        _id:"Kasara",
        name:"Dhrumil",
        email:"dh@g.com",
        address:"Kasara",
        pincode:"421602",
        role:"farmer"
    },
    {
        _id:"Sangli",
        name:"Utkarsh",
        email:"ut@g.com",
        address:"Sangli",
        pincode:"416406",
        role:"farmer"
    },
    {
        _id:"Dhule",
        name:"Bhavik",
        email:"bh@g.com",
        address:"Dhule",
        pincode:"424001",
        role:"farmer"
    }
]