module.exports.users=[
    {
        _id:"abc",
        name:"Nishtan",
        email:"ni@g.com",
        address:"Vikroli",
        pincode:"400079",
        role:"farmer"
    },
    {
        _id:"def",
        name:"Naman",
        email:"na@g.com",
        address:"Dombivali",
        pincode:"400612",
        role:"farmer"
    },{
        _id:"geh",
        name:"Sachit",
        email:"sa@g.com",
        address:"Virar",
        pincode:"401203",
        role:"farmer"
    },{
        _id:"hij",
        name:"Abhishek",
        email:"ab@g.com",
        address:"Kurla",
        pincode:"400070",
        role:"farmer"
    },
    {
        _id:"ijk",
        name:"Dhrumil",
        email:"dh@g.com",
        address:"Marine Lines",
        pincode:"400020",
        role:"farmer"
    },
    {
        _id:"nmp",
        name:"Utkarsh",
        email:"ut@g.com",
        address:"Bandra",
        pincode:"400050",
        role:"farmer"
    },
    {
        _id:"lmn",
        name:"Dombvali",
        email:"bh@g.com",
        address:"Dombivali",
        pincode:"400612",
        role:"farmer"
    }
]